### ISSUE TITLE
KeyError: 'propensity_score'

### ISSUE THREAD

**Issue by Feeeeeel** [WANGXinyiLinda/causal-balancing-for-domain-generalization#3]
When training phrase finished, I got this error:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/disk2/ywh/CB_DG/domainbed/scripts/train.py", line 180, in <module>
    if hparams['propensity_score']:
KeyError: 'propensity_score'

I did not find any information related to the keyword "propensity_score" in the hparams_registry.py and record.json files.
What should I do? Thanks for your reply.

**Comment by WANGXinyiLinda** [comment]
Just fixed the bug. It should be good now.

**Comment by Feeeeeel** [comment]
thanks!
