### ISSUE TITLE
AttributeError: 'CFmatchWrapper' object has no attribute 'oracle'

### ISSUE THREAD

**Issue by Feeeeeel** [WANGXinyiLinda/causal-balancing-for-domain-generalization#5]
Original Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk2/ywh/CB_DG/domainbed/match/utils.py", line 227, in __getitem__
    if self.oracle:
AttributeError: 'CFmatchWrapper' object has no attribute 'oracle'

It seems that self.oracle is not set in class CFmatchWrapper.

**Comment by WANGXinyiLinda** [comment]
Fixed by deleting self.oracle.
